import os
from osgeo import gdal
import numpy as np
import tqdm
import multiprocessing as mp
from functools import partial # Useful for passing fixed arguments to worker

import hazelbean as hb


def is_path_pog(path, check_tiled=True, full_check=False, raise_exceptions=False, verbose=False):
    
    is_pyramid = hb.is_path_global_pyramid(path, verbose=verbose)
    is_cog = hb.is_path_cog(path, check_tiled=check_tiled, full_check=full_check, raise_exceptions=raise_exceptions, verbose=verbose)

    if verbose:
        if is_pyramid:
            hb.log(f"Raster is a global pyramid: {path}")
        else:
            hb.log(f"Raster is not a global pyramid: {path}")
        if is_cog:
            hb.log(f"Raster is a COG: {path}")
        else:
            hb.log(f"Raster is not a COG: {path}")
            
    return is_pyramid and is_cog




# This worker function will be executed by each process in the pool.
# It needs to be defined at the top level of a module so it can be pickled.
def _worker_make_path_pog_starmap(input_file_path, specific_output_path, common_pog_options_dict):
    """
    Worker function for starmap.
    input_file_path: The specific input file for this task.
    specific_output_path: The specific output file path for this task (can be None).
    common_pog_options_dict: Dictionary of common options for hb.make_path_pog.
    """
    process_name = mp.current_process().name
    base_name = os.path.basename(input_file_path)

    try:
        hb.make_path_pog(
            input_file_path,
            output_raster_path=specific_output_path, # CRITICAL: Use the specific output path
            output_data_type=common_pog_options_dict.get('output_data_type', 'auto'),
            output_arcseconds=common_pog_options_dict.get('output_arcseconds'),
            overview_resampling_method=common_pog_options_dict.get('overview_resampling_method'),
            ndv=common_pog_options_dict.get('ndv'),
            compression=common_pog_options_dict.get('compression', "DEFLATE"),
            blocksize=common_pog_options_dict.get('blocksize', 512),
            verbose=common_pog_options_dict.get('verbose_hb_call', False),
            include_displaced_and_temp_files=common_pog_options_dict.get('include_displaced_and_temp_files', False),
            expand_to_global_extent=common_pog_options_dict.get('expand_to_global_extent', True),
        )
        output_msg_part = f" (output: {os.path.basename(specific_output_path)})" if specific_output_path else " (output: in-place/default)"
        return (input_file_path, True, f"Successfully processed by {process_name}{output_msg_part}")
    except Exception as e:
        return (input_file_path, False, f"Error in {process_name} for {base_name}: {type(e).__name__} - {e}")


def make_paths_pogs_in_parallel(
    input_folder_or_list,
    include_strings=None,
    include_extensions='.tif',
    exclude_strings=None,
    exclude_extensions=None,
    output_raster_path_suffix=None,
    output_data_type='auto',
    output_arcseconds=None,
    overview_resampling_method=None,
    ndv=None,
    compression="DEFLATE",
    blocksize=512,
    verbose_hb_call=False,
    max_workers=None,
    dry_run=False,
    dont_actually_do_it=False,  # older spelling of dry_run, kept for existing callers
    force_reprocess_pog=False,
    seek_recursively=True, 
    verbose=0,
    verbose_pog_check=0, 
    include_displaced_and_temp_files=False,
    expand_to_global_extent=True,
):
    """
    Lists raster files (input_folder_or_list is a folder to scan, or an explicit list of file paths),
    checks POG status, and processes them in parallel using hazelbean's make_path_pog and starmap.
    Output filenames can be generated by appending a suffix. dry_run lists what would be queued and
    returns simulated results without starting any worker.
    """
    dry_run = dry_run or dont_actually_do_it
    if not include_displaced_and_temp_files:
        # Leftovers of earlier in-place runs (<stem>_displaced_/_copy_/... files) would otherwise be
        # queued and then silently skipped by make_path_pog, reported as successes.
        exclude_strings = ([exclude_strings] if isinstance(exclude_strings, str) else list(exclude_strings or [])) + list(TEMP_NAME_MARKERS)

    if isinstance(input_folder_or_list, (list, tuple)):
        initial_paths_found = [os.path.abspath(i) for i in input_folder_or_list]
        missing = [i for i in initial_paths_found if not os.path.isfile(i)]
        if missing:
            print(f"Error: Input files not found: {missing}")
            return []
        if exclude_strings:
            initial_paths_found = [i for i in initial_paths_found if not any(x in os.path.basename(i) for x in exclude_strings)]
        print(f"Given {len(initial_paths_found)} files.")
    elif not os.path.isdir(os.path.abspath(input_folder_or_list)):
        print(f"Error: Input folder not found: {os.path.abspath(input_folder_or_list)}")
        return []
    elif seek_recursively:
        abs_input_folder = os.path.abspath(input_folder_or_list)
        print(f"Scanning folder: {abs_input_folder}")
    
        initial_paths_found = hb.list_filtered_paths_recursively(
            abs_input_folder,
            include_strings=include_strings,
            include_extensions=include_extensions,
            exclude_strings=exclude_strings,
            exclude_extensions=exclude_extensions,
            return_only_filenames=False
        )
    else:
        abs_input_folder = os.path.abspath(input_folder_or_list)
        print(f"Scanning folder: {abs_input_folder}")
        initial_paths_found = hb.list_filtered_paths_nonrecursively(
            abs_input_folder,
            include_strings=include_strings,
            include_extensions=include_extensions,
            exclude_strings=exclude_strings,
            exclude_extensions=exclude_extensions,
            return_only_filenames=False
        )

    if not initial_paths_found:
        print("No files found matching the initial filter criteria.")
        return []

    print(f"\nFound {len(initial_paths_found)} candidate files. Checking POG status...")

    # Prepare lists for starmap: one for input paths, one for corresponding output paths
    input_paths_for_processing = []
    output_paths_for_processing = []

    for i, path_to_check in enumerate(initial_paths_found):
        base_name = os.path.basename(path_to_check)
        is_pog = (hb.is_path_pog if expand_to_global_extent else hb.is_path_subpog)(path_to_check, verbose=verbose_pog_check)

        if is_pog and not force_reprocess_pog:
            print(f"  {i+1}. Skipping: {base_name} (is POG and not forcing reprocess)")
            continue
        
        action_reason = "(is POG but forcing reprocess)" if is_pog else "(not POG or POG status unknown)"
        print(f"  {i+1}. Queuing: {base_name} {action_reason}")
        
        input_paths_for_processing.append(path_to_check)

        # Determine the specific output path for this task
        if output_raster_path_suffix is not None:
            # Generate output path using the suffix
            specific_output_path = hb.suri(path_to_check, output_raster_path_suffix)
            output_paths_for_processing.append(specific_output_path)
        else:
            # No suffix means output_raster_path for hb.make_path_pog will be None
            # This typically implies in-place modification or hb default output naming.
            output_paths_for_processing.append(None)

    if not input_paths_for_processing:
        print("\nNo files to process after POG check.")
        return []

    print(f"\n{len(input_paths_for_processing)} files will be processed.")
    if dry_run:
        print("  (dry_run: these would be processed)")
        for i_path, o_path in zip(input_paths_for_processing, output_paths_for_processing):
            print(f"    Input: {os.path.basename(i_path)} -> Output: {os.path.basename(o_path) if o_path else 'None (in-place/default)'}")


    # Prepare common options for hb.make_path_pog
    # These are fixed for all tasks and will be passed via partial.
    common_pog_options = {
        'output_data_type': output_data_type,
        'output_arcseconds': output_arcseconds,
        'overview_resampling_method': overview_resampling_method,
        'ndv': ndv,
        'compression': compression,
        'blocksize': blocksize,
        'verbose_hb_call': verbose_hb_call,
        'include_displaced_and_temp_files': include_displaced_and_temp_files,
        'expand_to_global_extent': expand_to_global_extent,
    }

    # Prepare the arguments for starmap: a list of tuples,
    # where each tuple is (input_path, output_path)
    starmap_iterable = list(zip(input_paths_for_processing, output_paths_for_processing))

    # Use functools.partial to create a new worker function where common_pog_options_dict is pre-filled.
    # The resulting function will expect (input_file_path, specific_output_path) as arguments.
    worker_with_common_opts = partial(
        _worker_make_path_pog_starmap,
        common_pog_options_dict=common_pog_options
    )

    if max_workers is None:
        max_workers = os.cpu_count() - 2
    max_workers = min(max_workers, len(starmap_iterable)) # Don't use more processes than tasks

    results = []
    if max_workers <= 0:
        print("No tasks to process or max_workers is 0 or less. Skipping parallel execution.")
    else:
        print(f"\nStarting parallel processing with {max_workers} worker(s)...")
        if not dry_run:
            with mp.Pool(processes=max_workers) as pool:
                # pool.starmap expects an iterable of argument tuples.
                # For each (in_path, out_path) in starmap_iterable, it effectively calls:
                #   _worker_make_path_pog_starmap(in_path, out_path, common_pog_options_dict=common_pog_options)
                results = pool.starmap(worker_with_common_opts, starmap_iterable)
        else:
            print(f"\nSKIPPING ACTUAL PROCESSING due to dry_run=True.")
            # Simulate results if needed for testing downstream logic
            for in_path, out_path in starmap_iterable:
                results.append((in_path, True, f"Simulated success by DUMMY_PROCESS (output: {os.path.basename(out_path) if out_path else 'None'})"))


    print("\n--- Processing Summary ---")
    success_count = 0
    failure_count = 0
    for file_path, success, message in results: # Assuming worker returns this tuple
        base_name = os.path.basename(file_path)
        if success:
            print(f"SUCCESS: {base_name} - {message}")
            success_count += 1
        else:
            print(f"FAILURE: {base_name} - {message}")
            failure_count += 1
    
    print(f"\nFinished processing. {success_count} successful, {failure_count} failed.")
    return results
 
  
# Name fragments make_path_pog inserts into the files it leaves beside an input (see the skip check in make_path_pog).
# The keyword list itself lives in os_utils, beside hb.remove_temp_files_recursively which cleans them up.
TEMP_NAME_MARKERS = tuple('_' + k + '_' for k in hb.TEMP_FILE_KEYWORDS)


def _write_cog_with_pyramid_overviews(current_path, output_raster_path, overview_levels, overview_resampling_method, output_data_type, ndv, compression, blocksize, verbose=False):
    """The POG finishing sequence shared by make_path_pog and the subpog writers: exact stats, internal overviews at
    overview_levels, then a copy through the COG driver to output_raster_path. current_path is modified in place (stats, overviews)."""
    # Open the source raster in UPDATE MODE so it writes the overviews as internal
    if verbose:
        hb.log(f"Opening {current_path} for overview building.")
    src_ds = gdal.OpenEx(current_path, gdal.GA_Update, open_options=["IGNORE_COG_LAYOUT_BREAK=YES"])
    if not src_ds:
        raise ValueError(f"Unable to open raster: {current_path}")

    # Exact statistics, computed on the update-mode dataset so they are written INTO the TIFF. A read-only
    # compute (gdalinfo -stats, or ComputeStatistics on a read-only open) lands in a .aux.xml sidecar, which
    # is invisible to the COG copy below whenever GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR is set.
    if verbose:
        hb.log(f"Computing exact statistics for {current_path}.")
    stats_by_band = {i: src_ds.GetRasterBand(i).ComputeStatistics(False) for i in range(1, src_ds.RasterCount + 1)}

    # Remove existing overviews (if any)
    src_ds.BuildOverviews(None, [])     
        
    if overview_resampling_method is None:
        overview_resampling_method = hb.pyramid_resampling_algorithms_by_data_type[output_data_type] 
    
    # Set the overview levels based on the pyramid arcseconds
    
    if verbose:
        hb.log(f"Building overviews for {current_path} with levels {overview_levels}...")
    src_ds.BuildOverviews(overview_resampling_method.upper(), overview_levels, hb.make_gdal_callback(f'Building overviews for {current_path}'))

    # Re-apply the statistics after overview building (BuildOverviews can drop band metadata), then close.
    for i, (stat_min, stat_max, stat_mean, stat_std) in stats_by_band.items():
        band = src_ds.GetRasterBand(i)
        for key, value in (('STATISTICS_MINIMUM', stat_min), ('STATISTICS_MAXIMUM', stat_max), ('STATISTICS_MEAN', stat_mean), ('STATISTICS_STDDEV', stat_std)):
            band.SetMetadataItem(key, str(value))
        band.SetMetadataItem('STATISTICS_APPROXIMATE', 'NO')
    del src_ds    
    
    # Reopen it to use it as a copy target
    if verbose:
        hb.log(f"Reopening {current_path} for COG creation...")
    src_ds = gdal.OpenEx(current_path, gdal.GA_ReadOnly)
    
    # Define creation options for COG
    creation_options = [
        f"COMPRESS={compression}",
        f"BLOCKSIZE={blocksize}",  
        f"BIGTIFF=YES", 
        f"OVERVIEW_COMPRESS={compression}",        
        f"RESAMPLING={overview_resampling_method}",
        # f"OVERVIEWS=IGNORE_EXISTING",
        f"OVERVIEW_RESAMPLING={overview_resampling_method}",
    ]

    cog_driver = gdal.GetDriverByName('COG')
    if cog_driver is None:
        raise RuntimeError("COG driver is not available in this GDAL build.")    
    
    if ndv is not None and src_ds is not None:
        for i in range(1, src_ds.RasterCount + 1):
            band = src_ds.GetRasterBand(i)
            band.SetNoDataValue(ndv)
            
    # Actually create the COG
    force_verbose = True
    if verbose or force_verbose:
        hb.log(f"Creating COG at {output_raster_path}. Abs path: {os.path.abspath(output_raster_path)}, Norm path: {os.path.normpath(output_raster_path)}")   
    
    dst_ds = cog_driver.CreateCopy(
        output_raster_path,
        src_ds,
        strict=0,  # set to 1 to fail on any “creation option not recognized”
        options=creation_options,
        callback=hb.make_gdal_callback(f'cog_driver creating copy at {output_raster_path}')
    )        
    
    dst_ds = None
    


def is_path_subpog(path, check_tiled=True, full_check=False, raise_exceptions=False, verbose=False):
    """A subpog is a POG in every respect except extent: pyramid-aligned sub-extent (hb.is_path_subglobal_pyramid) and a valid COG."""
    return hb.is_path_subglobal_pyramid(path, verbose=verbose) and hb.is_path_cog(path, check_tiled=check_tiled, full_check=full_check, raise_exceptions=raise_exceptions, verbose=verbose)


def write_subpog_from_pog_window(pog_path, bb, output_path, compression='DEFLATE', blocksize=512, verbose=False):
    """Cut bb out of a POG and write it as a subpog at output_path. bb must be pyramid-aligned at the POG's resolution
    (snap it with hb.snap_bb_to_pyramid first); the overview chain is truncated to the levels that divide bb."""
    arcseconds = hb.get_cell_size_from_path_in_arcseconds(pog_path, force_to_pyramid=True)
    output_data_type = hb.get_datatype_from_uri(pog_path)
    ndv = hb.no_data_values_by_gdal_type[output_data_type][0]
    stem = os.path.splitext(os.path.basename(output_path))[0]
    temp_path = hb.temp('.tif', stem + '_translate', True, tag_along_file_extensions=['.aux.xml'])  # in hb.get_temp_dir(), so tile folders stay clean
    gdal.Translate(temp_path, pog_path, projWin=[bb[0], bb[3], bb[2], bb[1]], noData=ndv, creationOptions=hb.globals.PRECOG_GTIFF_CREATION_OPTIONS_LIST)
    _write_cog_with_pyramid_overviews(temp_path, output_path, hb.get_pyramid_overview_levels_for_bb(arcseconds, bb), None, output_data_type, ndv, compression, blocksize, verbose)
    return output_path


def tile_pog_to_tileset(pog_path, output_dir=None, tile_degrees=None, skip_empty_tiles=True, verbose=False):
    """Cut a global POG into corner-named subpog tiles plus a VRT that presents them as the global raster again.

    Tiles go in output_dir (default <pog dir>/<stem>_<sec>sec_<deg>deg/) named by hb.get_tile_filename; the VRT is
    written beside that folder with the same name and .vrt. tile_degrees defaults to hb.pyramid_tile_degrees for the
    POG's resolution and must divide 180 and be a whole number of cells. With skip_empty_tiles, tiles that are
    entirely nodata are not written (the VRT reads them as nodata). Returns the VRT path.
    """
    if not is_path_pog(pog_path, verbose=verbose):
        raise ValueError(f'Not a POG, refusing to tile it: {pog_path}')
    arcseconds = hb.get_cell_size_from_path_in_arcseconds(pog_path, force_to_pyramid=True)
    if tile_degrees is None:
        tile_degrees = hb.pyramid_tile_degrees[arcseconds]
    if tile_degrees is None:
        raise ValueError(f'{int(arcseconds)} arcseconds is not a tiled resolution (see hb.pyramid_tile_degrees); pass tile_degrees to force a tiling.')
    stem = os.path.splitext(os.path.basename(pog_path))[0]
    tileset_name = f'{stem}_{int(arcseconds)}sec_{int(tile_degrees)}deg'
    if output_dir is None:
        output_dir = os.path.join(os.path.dirname(os.path.abspath(pog_path)), tileset_name)
    os.makedirs(output_dir, exist_ok=True)
    ds = gdal.Open(pog_path); band = ds.GetRasterBand(1); ndv = band.GetNoDataValue()
    res = hb.pyramid_compatible_resolutions[arcseconds]
    n_written = 0
    for corner in hb.list_tile_corner_strings(tile_degrees):
        bb = hb.get_tile_bb_from_corner_string(corner, tile_degrees)
        if skip_empty_tiles:
            xoff, yoff, size = int(round((bb[0] + 180) / res)), int(round((90 - bb[3]) / res)), int(round(tile_degrees / res))
            if np.all(band.ReadAsArray(xoff, yoff, size, size) == ndv):
                continue
        write_subpog_from_pog_window(pog_path, bb, os.path.join(output_dir, hb.get_tile_filename(stem, arcseconds, corner, tile_degrees)), verbose=verbose)
        n_written += 1
    ds = None
    if verbose:
        hb.log(f'Wrote {n_written} tiles to {output_dir}')
    return build_pog_tileset_vrt(output_dir, os.path.join(os.path.dirname(output_dir), tileset_name + '.vrt'))


def build_pog_tileset_vrt(tile_dir, vrt_path=None):
    """Index the corner-named tiles in tile_dir as one global raster: a VRT with the exact global geotransform, the standard
    nodata, and relative source paths, so missing tiles read as nodata and the folder plus VRT move together. Returns vrt_path."""
    tiles = sorted(i for i in hb.list_filtered_paths_nonrecursively(tile_dir, include_extensions='.tif') if _is_tile_filename(i))
    if not tiles:
        raise ValueError(f'No corner-named tiles (<stem>_<sec>sec_<deg>deg_<corner>.tif) in {tile_dir}')
    stem, arcseconds, tile_degrees, _ = hb.parse_tile_filename(tiles[0])
    res = hb.pyramid_compatible_resolutions[arcseconds]
    ndv = hb.no_data_values_by_gdal_type[hb.get_datatype_from_uri(tiles[0])][0]
    if vrt_path is None:
        vrt_path = os.path.join(os.path.dirname(os.path.abspath(tile_dir)), f'{stem}_{int(arcseconds)}sec_{int(tile_degrees)}deg.vrt')
    gdal.BuildVRT(vrt_path, tiles, options=gdal.BuildVRTOptions(outputBounds=(-180, -90, 180, 90), xRes=res, yRes=res, VRTNodata=ndv, srcNodata=ndv)).FlushCache()
    return vrt_path


def _is_tile_filename(path):
    try:
        hb.parse_tile_filename(path); return True
    except ValueError:
        return False


def is_path_pog_tileset(vrt_path, verbose=False):
    """True if vrt_path presents a set of subpog tiles as the global raster: global pyramid geotransform on the VRT, every
    source a corner-named tile whose extent matches its name, and every tile a subpog."""
    ds = gdal.Open(vrt_path)
    if ds is None:
        return False
    sources = [i for i in ds.GetFileList()[1:]]
    gt = ds.GetGeoTransform(); ds = None
    if not sources:
        if verbose: hb.log('Not a POG tileset: the VRT has no sources: ' + str(vrt_path))
        return False
    stem, arcseconds, tile_degrees, _ = hb.parse_tile_filename(sources[0])
    expected = hb.pyramid_compatible_geotransforms[arcseconds]
    if any(abs(a - b) > 1e-9 for a, b in zip(gt, expected)):
        if verbose: hb.log(f'Not a POG tileset: VRT geotransform {gt} is not the global {expected}: {vrt_path}')
        return False
    for tile in sources:
        _, sec, deg, corner = hb.parse_tile_filename(tile)
        bb = hb.get_tile_bb_from_corner_string(corner, deg)
        tgt = hb.get_geotransform_path(tile); shape = hb.get_shape_from_dataset_path(tile)
        if sec != arcseconds or deg != tile_degrees or abs(tgt[0] - bb[0]) > 1e-9 or abs(tgt[3] - bb[3]) > 1e-9 or abs(shape[1] * tgt[1] - deg) > 1e-6 or abs(shape[0] * -tgt[5] - deg) > 1e-6:
            if verbose: hb.log(f'Not a POG tileset: {tile} does not cover the extent its name claims ({bb})')
            return False
        if not is_path_subpog(tile, verbose=verbose):
            if verbose: hb.log(f'Not a POG tileset: {tile} is not a subpog')
            return False
    return True


def make_path_pog(input_raster_path,
                  output_raster_path=None,
                  output_data_type=None,
                  output_arcseconds=None,
                  ndv=None,
                  overview_resampling_method=None,
                  compression="DEFLATE",
                  blocksize=512,
                  force_rewrite=False,
                  value_reclassification_dict=None,
                  ndv_above=None,
                  ndv_below=None,
                  remove_intermediate_files=True,
                  remove_displaced_files=False,
                  verbose=False,
                  include_displaced_and_temp_files=False,
                  expand_to_global_extent=True):

    """ Create a Pog (pyramidal cog) from input_raster_path. Writes in-place if output_raster_path is not set. Chooses correct values for
    everything else if not set.

    expand_to_global_extent=True (default) makes a POG: a non-global input is placed on the global grid and padded with
    nodata. expand_to_global_extent=False makes a SUBPOG instead: the input keeps its footprint, snapped outward to the
    pyramid grid at the output resolution (hb.snap_bb_to_pyramid), with the overview chain truncated to the levels that
    divide that extent. Both are no-ops on an input that already is the requested kind.

    output_arcseconds, if given, sets the resolution of the output POG explicitly: the input is resampled to the
    canonical match raster at that resolution. Required when the input is not close to any supported pyramid
    resolution; also usable to deliberately convert between supported resolutions. When it requests a genuinely
    coarser grid, resampling aggregates (mode for integer types, average for floats) rather than point-sampling."""

    # Check if input exists
    if not hb.path_exists(input_raster_path, verbose=verbose):
        raise FileNotFoundError(f"Input raster does not exist: {input_raster_path} at abs path {hb.path_abs(input_raster_path)}")

    # An in-place conversion leaves the original beside the POG as <name>_displaced_<stamp>.tif, and its
    # intermediates as <name>_copy_<stamp>.tif etc. (kept when remove_intermediate_files=False, or after a
    # crash). A directory walk that reruns would otherwise poggerize those too; skip them by default.
    if any(marker in os.path.basename(input_raster_path) for marker in TEMP_NAME_MARKERS) and not include_displaced_and_temp_files:
        if verbose:
            hb.log(f"Skipping displaced/temp file (pass include_displaced_and_temp_files=True to convert it): {input_raster_path}")
        return

    if output_arcseconds is not None and output_arcseconds not in hb.pyramid_compatible_resolutions:
        raise ValueError(f"output_arcseconds {output_arcseconds} is not a supported pyramid resolution. "
                         f"Supported values (arcseconds): 1, 10, 30, 150, 300, 900, 1800, 3600, 7200, 14400, 36000.")

    # Do a fast check to see if it's pog (or, when not expanding, subpog).
    is_path_requested_kind = is_path_pog if expand_to_global_extent else is_path_subpog
    is_path_requested_pyramid = hb.is_path_global_pyramid if expand_to_global_extent else hb.is_path_subglobal_pyramid
    needs_censoring = False
    if not is_path_requested_pyramid(input_raster_path, verbose):
        if verbose:
            hb.log(f"Raster is not a {'global' if expand_to_global_extent else 'sub-global'} pyramid. {input_raster_path}")
    else:        
        if ndv_above is not None or ndv_below is not None:
            stats_by_band = hb.get_stats_from_geotiff(input_raster_path)            
            if ndv_above < stats_by_band[1]['max']:
                if verbose:
                    hb.log(f"Raster is not a global pyramid because it has values above the ndv_above threshold. {input_raster_path}")
                needs_censoring = True
            if ndv_below > stats_by_band[1]['min']:
                if verbose:
                    hb.log(f"Raster is not a global pyramid because it has values below the ndv_below threshold. {input_raster_path}")
                needs_censoring = True  

        needs_reclassification = False
        if value_reclassification_dict is not None:
            needs_reclassification = True

        # A requested output_arcseconds different from the input's resolution means the input
        # cannot be accepted as-is even if it already validates as a POG.
        needs_resolution_change = False
        if output_arcseconds is not None:
            input_resolution = hb.determine_pyramid_resolution(input_raster_path)
            if input_resolution is None or hb.pyramid_compatible_resolution_to_arcseconds[input_resolution] != float(output_arcseconds):
                needs_resolution_change = True

        # Do a full check to see if the input is already a POG. If so, skip it.
        if is_path_requested_kind(input_raster_path, verbose=verbose) and not force_rewrite and not needs_censoring and not needs_reclassification and not needs_resolution_change:
            if verbose:
                hb.log(f"Raster is already a POG: {input_raster_path}")
            return
        
    # Make a local copy at a temp file to process on to avoid corrupting the original.
    # Intermediates are named <input stem>_<step>_<stamp>.tif so they sort beside their source.
    input_dir = os.path.dirname(input_raster_path)
    input_stem = os.path.splitext(os.path.basename(input_raster_path))[0]
    temp_copy_path = hb.temp('.tif', input_stem + '_copy', remove_intermediate_files, folder=input_dir, tag_along_file_extensions=['.aux.xml'])
    temp_translate_path = hb.temp('.tif', input_stem + '_translate', remove_intermediate_files, folder=input_dir, tag_along_file_extensions=['.aux.xml'])
    
    # Ensure output directory exists
    try:
        os.makedirs(os.path.dirname(temp_copy_path), exist_ok=True)       
    except:
        pass
    
    input_data_type = hb.get_datatype_from_uri(input_raster_path)
    
    ### WARNING: Forcing data type optimizations is a bad idea! Increment up the following number to represent the number of failed attempts to try it: attempts = 2
    # OUTDATED POG SPECIFIC HERE. Note the draconian forcing here of bytes into int64s
    # WAIT! Although gdal does support int64, the geotiff driver does not. It internally converts to float64 as a result.
    # One option would be to use ... dammit...
    # input_data_type = hb.get_datatype_from_uri(input_raster_path)
    # if output_data_type == 'auto':
    #     if input_data_type in [1, 2, 3, 4, 5, 12, 13]:
    #         output_data_type = 5
    #         output_data_type_object = gdal.GDT_Int32
    #     elif input_data_type in [6]:
    #         output_data_type = 6
    #         output_data_type_object = gdal.GDT_Float32
    #     elif input_data_type in [7, 8, 9, 10, 11]:
    #         output_data_type = 7
    #         output_data_type_object = gdal.GDT_Float64
    
    if output_data_type is None or output_data_type == 'auto':
        output_data_type = input_data_type 

    if output_data_type != input_data_type:
        if verbose:            
            hb.log(f"Changing data type from {input_data_type} to {output_data_type} for {input_raster_path}")
        output_data_type = hb.gdal_number_to_gdal_type[output_data_type]
        gdal.Translate(temp_translate_path, input_raster_path, outputType=output_data_type, options=['-co', f'COMPRESS={compression}'], callback=hb.make_gdal_callback(f"Translating to change datatype on {hb.path_filename(input_raster_path)} to {temp_translate_path} to be datatype {output_data_type}."))
        current_path = temp_translate_path
    else:
        if verbose:
            hb.log(f"Data type is already {output_data_type} for {input_raster_path}, so just copying to {temp_copy_path}.")
        hb.path_copy(input_raster_path, temp_copy_path) # Can just copy it direclty without accessing the raster.        
        current_path = temp_copy_path

    # Get the resolution of the output: explicit if output_arcseconds was given, otherwise snapped from the input.
    if output_arcseconds is not None:
        arcseconds = output_arcseconds
        degrees = hb.pyramid_compatible_resolutions[output_arcseconds]
    else:
        try:
            degrees = hb.get_cell_size_from_path(current_path, force_to_pyramid=True)
            arcseconds = hb.get_cell_size_from_path_in_arcseconds(current_path, force_to_pyramid=True)
        except ValueError as e:
            raise ValueError(f"Input raster {input_raster_path} is not close to any supported pyramid resolution, so "
                             f"make_path_pog cannot infer which canonical match to use. Pass output_arcseconds to choose "
                             f"the output resolution explicitly (supported: 1, 10, 30, 150, 300, 900, 1800, 3600, 7200, "
                             f"14400, 36000).") from e

    original_output_raster_path = output_raster_path
    if output_raster_path is None:        
        output_raster_path = hb.temp('.tif', input_stem + '_pog', remove_at_exit=False, folder=os.path.dirname(input_raster_path), tag_along_file_extensions=['.aux.xml'])
        
    ndv = hb.no_data_values_by_gdal_type[output_data_type][0] # NOTE AWKWARD INCLUSINO OF zero as second option to work with faster_zonal_stats
    
    if output_data_type <= 5 or output_data_type == 12 or output_data_type == 13:
        resample_method = 'nearest'
    else:
        resample_method = 'bilinear'

    # When output_arcseconds requests a genuinely coarser grid (not just snapping a near-pyramid input),
    # aggregate rather than point-sample: mode for integer types, average for floats, mirroring the overview logic.
    if output_arcseconds is not None:
        native_degrees = hb.get_cell_size_from_path(current_path)
        if native_degrees < hb.pyramid_compatible_resolution_bounds[output_arcseconds][0]:
            resample_method = hb.pyramid_resampling_algorithms_by_data_type[output_data_type]

    # POG SPECIFIC DIFFERENCE HERE: Handles the case where the raster is not global.
    gt = hb.get_geotransform_path(input_raster_path)
    gt_pyramid = hb.get_global_geotransform_from_resolution(degrees)
    input_shape = hb.get_shape_from_dataset_path(input_raster_path)
    input_bb = [gt[0], gt[3] + input_shape[0] * gt[5], gt[0] + input_shape[1] * gt[1], gt[3]]
    if expand_to_global_extent:
        target_bb = None  # resample_to_match uses the match raster's global frame
        needs_reframing = gt != gt_pyramid
        if needs_reframing and (verbose or gt[1] == degrees):
            hb.log(f"make_path_pog: expanding {input_raster_path} from extent {[round(i, 6) for i in input_bb]} to the global "
                   f"{int(round(360 / degrees))} x {int(round(180 / degrees))} grid at {int(arcseconds)} arcseconds (pass expand_to_global_extent=False for a subpog).")
    else:
        target_bb = hb.snap_bb_to_pyramid(input_bb, arcseconds)
        needs_reframing = abs(gt[1] - degrees) > 1e-12 or any(abs(a - b) > 1e-9 for a, b in zip(input_bb, target_bb))
        if verbose:
            hb.log(f"make_path_pog: subpog extent {target_bb} (input extent {[round(i, 6) for i in input_bb]})")

    if needs_reframing:
        # Resolve the canonical match raster for the output resolution through the get_path ladder
        # (project dirs, base_data, shared data roots, cloud download) rather than a hardcoded location.
        match_path = hb.get_path(hb.ha_per_cell_ref_paths[arcseconds])
        resample_temp_path = hb.temp('.tif', input_stem + '_resample', remove_intermediate_files, folder=os.path.dirname(input_raster_path), tag_along_file_extensions=['.aux.xml'])
        if verbose:
            hb.log(f"Resampling {current_path} to match {match_path}. Saving at {resample_temp_path}.")
        hb.resample_to_match(
            current_path,
            match_path,
            resample_temp_path,
            resample_method=resample_method,
            output_data_type=output_data_type,
            src_ndv=None,
            ndv=ndv,
            s_srs_wkt=None,
            compress=True,
            ensure_fits=False,
            gtiff_creation_options=hb.globals.PRECOG_GTIFF_CREATION_OPTIONS_LIST,
            calc_raster_stats=False,
            add_overviews=False,
            pixel_size_override=None,
            target_aligned_pixels=True, # DOESNT DO ANYTHING BUT DONT WANT TO FUBAR STUFF
            bb_override=target_bb,
            verbose=False, 
        )
        current_path = resample_temp_path
    
    if (ndv_above is not None or ndv_below is not None) and needs_censoring:
        censor_temp_path = hb.temp('.tif', input_stem + '_censor', remove_intermediate_files, folder=os.path.dirname(input_raster_path), tag_along_file_extensions=['.aux.xml'])
        if ndv_above and not ndv_below:
            def op(x):
                return np.where(x > ndv_above, ndv, x)
        elif ndv_below and not ndv_above:
            def op(x):
                return np.where(x < ndv_below, ndv, x)
        elif ndv_above and ndv_below:
            def op(x):
                return np.where((x > ndv_above) | (x < ndv_below), ndv, x)
            
        hb.log(f"Censoring {current_path} with ndv_above={ndv_above} and ndv_below={ndv_below}. Saving at {censor_temp_path}.")
        hb.raster_calculator_flex(current_path, op, censor_temp_path, output_data_type=output_data_type, ndv=ndv, compression=compression, verbose=verbose)
        current_path = censor_temp_path
    
    if value_reclassification_dict is not None:
        reclassify_temp_path = hb.temp('.tif', input_stem + '_reclassify', remove_intermediate_files, '.', tag_along_file_extensions=['.aux.xml'])

        hb.log(f"Reclassifying {current_path} with {value_reclassification_dict}. Saving at")
        hb.reclassify_raster_hb(current_path, value_reclassification_dict, reclassify_temp_path)
     
    overview_levels = hb.pyramid_compatible_overview_levels[arcseconds] if expand_to_global_extent else hb.get_pyramid_overview_levels_for_bb(arcseconds, target_bb)
    _write_cog_with_pyramid_overviews(current_path, output_raster_path, overview_levels,
                                      overview_resampling_method, output_data_type, ndv, compression, blocksize, verbose)

    if not is_path_requested_kind(output_raster_path, verbose=verbose) and verbose:
        hb.log(f"Failed to create {'POG' if expand_to_global_extent else 'subpog'}: {output_raster_path} at abs path {hb.path_abs(output_raster_path)}")
    
    if original_output_raster_path is None:
        # The swap only renames the main file, so an input's external .ovr / .aux.xml would stay
        # behind under the new POG's name and shadow its internal overviews (is_path_pog then
        # fails on the result). Move them with the displaced original, or drop them with it.
        displaced_path = hb.rsuri(input_raster_path, 'displaced')
        for ext in ('.ovr', '.aux.xml'):
            if os.path.exists(input_raster_path + ext):
                if remove_displaced_files:
                    os.remove(input_raster_path + ext)
                else:
                    os.rename(input_raster_path + ext, displaced_path + ext)
        hb.displace_file(output_raster_path, input_raster_path, displaced_path=displaced_path, delete_original=remove_displaced_files)


    
def write_pog_of_value_from_scratch(output_path, value, arcsecond_resolution, output_data_type, ndv=None, overview_resampling_method=None, compression='DEFLATE', blocksize='512', verbose=False):
    # Define creation options for COG
    precog_gtiff_creation_options = [
        f"COMPRESS={compression}",
        f"BLOCKXSIZE={str(blocksize)}",  
        f"BLOCKYSIZE={str(blocksize)}",  
        f"BIGTIFF=YES", 
        "TILED=YES",
    ]

        
    if ndv is None:
        ndv = hb.no_data_values_by_gdal_type[output_data_type][0] 

    if overview_resampling_method is None:
            overview_resampling_method = hb.pyramid_resampling_algorithms_by_data_type[output_data_type] 

    geotransform = hb.pyramid_compatible_geotransforms[float(arcsecond_resolution)]
    projection = hb.wgs_84_wkt
    x_size = hb.pyramid_compatable_shapes[float(arcsecond_resolution)][0]
    y_size = hb.pyramid_compatable_shapes[float(arcsecond_resolution)][1]

    
    # Make a temp geotiff based on match
    temp_path = hb.temp('.tif', filename_start=os.path.splitext(os.path.basename(output_path))[0] + '_b4_cog', remove_at_exit=True)
    driver = gdal.GetDriverByName('GTiff')
    tmp_ds = driver.Create(temp_path, x_size, y_size, 1, output_data_type, options=precog_gtiff_creation_options)
    tmp_ds.SetGeoTransform(geotransform)
    tmp_ds.SetProjection(projection)    
    
    # Memory safe (hopefully) way to write the value to the raster, row by row
    value_row = np.full((1, x_size), value, dtype=hb.gdal_number_to_numpy_type[output_data_type])

    # Initialize accumulators for statistics
    total_sum = 0.0
    total_sq_sum = 0.0
    total_count = 0
    global_min = np.inf
    global_max = -np.inf        
    
    band = tmp_ds.GetRasterBand(1)
    for row in tqdm.tqdm(range(y_size)):
        # hb.print_in_place('Writing row ' + str(row) + ' of ' + str(y_size))
        band.WriteArray(value_row, xoff=0, yoff=row)
      
        # Update statistics incrementally
        total_sum += value_row.sum()
        total_sq_sum += np.square(value_row).sum()
        total_count += value_row.size
        global_min = min(global_min, np.min(value_row))
        global_max = max(global_max, np.max(value_row))    

    mean = total_sum / total_count if total_count else 0
    variance = (total_sq_sum / total_count - mean ** 2) if total_count else 0
    variance = max(variance, 0)  # safeguard against negative variance
    stddev = np.sqrt(variance)
        
    # Build Overviews
    tmp_ds.GetRasterBand(1).SetNoDataValue(ndv)    
    tmp_ds.BuildOverviews(None, []) # Remove existing overviews (if any) 
    
    resampling_algorithm = hb.pyramid_resampling_algorithms_by_data_type[output_data_type]    
    if overview_resampling_method is None:
        overview_resampling_method = resampling_algorithm
    
    # Set the overview levels based on the pyramid arcseconds
    overview_levels = hb.pyramid_compatible_overview_levels[arcsecond_resolution]
    tmp_ds.BuildOverviews(overview_resampling_method.upper(), overview_levels, callback=hb.make_gdal_callback('Building overviews for ' + str(output_path)))
    
    tmp_ds.FlushCache()
    del tmp_ds  # Close temp dataset
    
    # Add statistics to the temp dataset
    hb.add_stats_to_geotiff_with_gdal(temp_path, approx_ok=False, force=True, verbose=verbose)

    # Step 2: Convert temporary GTiff to COG using CreateCopy
    cog_driver = gdal.GetDriverByName('COG')
    cog_creation_options = [
        f'COMPRESS={compression}',
        f'BLOCKSIZE={blocksize}',
        'BIGTIFF=YES',
        # 'OVERVIEWS=IGNORE_EXISTING'
    ]

    tmp_ds = gdal.Open(temp_path)
    cog_ds = cog_driver.CreateCopy(output_path, tmp_ds, options=cog_creation_options)

    if cog_ds is None:
        raise RuntimeError('Failed to create COG dataset.')

    # Cleanup
    del cog_ds
    del tmp_ds


def write_pog_of_value_from_match(output_path, match_path, value, output_data_type=None, ndv=None, overview_resampling_method=None, compression='DEFLATE', blocksize='512', verbose=False):
    
    # Define creation options for COG
    precog_gtiff_creation_options = [
        f"COMPRESS={compression}",
        f"BLOCKXSIZE={str(blocksize)}",  
        f"BLOCKYSIZE={str(blocksize)}",  
        f"BIGTIFF=YES", 
        f"TILED=YES", 
    ]
    
    # Check if match exists
    if not hb.path_exists(match_path, verbose=verbose):
        raise FileNotFoundError(f"Input raster does not exist: {match_path} at abs path {hb.path_abs(match_path)}")
    
    if output_data_type is None:
        output_data_type = hb.get_datatype_from_uri(match_path)
        
    if ndv is None:
        ndv = hb.no_data_values_by_gdal_type[output_data_type][0] 

    if overview_resampling_method is None:
            overview_resampling_method = hb.pyramid_resampling_algorithms_by_data_type[output_data_type] 
            
    # Open existing raster to match
    src_ds = gdal.Open(match_path)
    geotransform = src_ds.GetGeoTransform()
    projection = src_ds.GetProjection()
    x_size = src_ds.RasterXSize
    y_size = src_ds.RasterYSize
    degrees = hb.get_cell_size_from_path(match_path)
    arcseconds = hb.get_cell_size_from_path_in_arcseconds(match_path)        
    
    # Make a temp geotiff based on match
    temp_path = hb.temp('.tif', filename_start=os.path.splitext(os.path.basename(output_path))[0] + '_b4_cog', remove_at_exit=True)
    driver = gdal.GetDriverByName('GTiff')
    tmp_ds = driver.Create(temp_path, x_size, y_size, 1, output_data_type, options=precog_gtiff_creation_options)
    tmp_ds.SetGeoTransform(geotransform)
    tmp_ds.SetProjection(projection)    
    
    # Memory safe (hopefully) way to write the value to the raster, row by row
    value_row = np.full((1, x_size), value, dtype=hb.gdal_number_to_numpy_type[output_data_type])

    # Initialize accumulators for statistics
    total_sum = 0.0
    total_sq_sum = 0.0
    total_count = 0
    global_min = np.inf
    global_max = -np.inf        
    
    band = tmp_ds.GetRasterBand(1)
    for row in tqdm.tqdm(range(y_size)):
        # hb.print_in_place('Writing row ' + str(row) + ' of ' + str(y_size))
        band.WriteArray(value_row, xoff=0, yoff=row)
      
        # Update statistics incrementally
        total_sum += value_row.sum()
        total_sq_sum += np.square(value_row).sum()
        total_count += value_row.size
        global_min = min(global_min, np.min(value_row))
        global_max = max(global_max, np.max(value_row))    

    mean = total_sum / total_count if total_count else 0
    variance = (total_sq_sum / total_count - mean ** 2) if total_count else 0
    variance = max(variance, 0)  # safeguard against negative variance
    stddev = np.sqrt(variance)
        
    # Build Overviews
    tmp_ds.GetRasterBand(1).SetNoDataValue(ndv)    
    tmp_ds.BuildOverviews(None, []) # Remove existing overviews (if any) 
    
    resampling_algorithm = hb.pyramid_resampling_algorithms_by_data_type[output_data_type]    
    if overview_resampling_method is None:
        overview_resampling_method = resampling_algorithm
    
    # Set the overview levels based on the pyramid arcseconds
    overview_levels = hb.pyramid_compatible_overview_levels[arcseconds]
    tmp_ds.BuildOverviews(overview_resampling_method.upper(), overview_levels, callback=hb.make_gdal_callback('Building overviews for ' + str(output_path)))
    
    tmp_ds.FlushCache()
    del tmp_ds  # Close temp dataset

    # Set statistics, ensuring they are not approximate
    hb.add_stats_to_geotiff_with_gdal(temp_path, approx_ok=False, force=True, verbose=verbose)
    
    # Step 2: Convert temporary GTiff to COG using CreateCopy
    cog_driver = gdal.GetDriverByName('COG')
    cog_creation_options = [
        f'COMPRESS={compression}',
        f'BLOCKSIZE={blocksize}',
        'BIGTIFF=YES',
        'NUM_THREADS=ALL_CPUS',
        # 'OVERVIEWS=IGNORE_EXISTING'
    ]

    tmp_ds = gdal.Open(temp_path)
    cog_ds = cog_driver.CreateCopy(output_path, tmp_ds, options=cog_creation_options)

    if cog_ds is None:
        raise RuntimeError('Failed to create COG dataset.')

    # Cleanup
    del cog_ds
    del tmp_ds
    del src_ds

